object FormExec: TFormExec
  Left = 0
  Top = 0
  Caption = 'FormExec'
  ClientHeight = 202
  ClientWidth = 447
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PrintScale = poNone
  Scaled = False
  OnKeyUp = FormKeyUp
  PixelsPerInch = 96
  TextHeight = 13
end
